"""Initial migration

Revision ID: 9fa75120274b
Revises: 
Create Date: 2024-07-01 08:21:35.911727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa75120274b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_uniform')
    with op.batch_alter_table('uniform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('school_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uniform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('size',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('school_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('photo_url')

    op.create_table('_alembic_tmp_uniform',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('school_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color_code', sa.VARCHAR(length=7), nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
